// Application dependencies
global using Microsoft.AspNetCore.Identity;
global using AutoMapper;
// Unit testing
global using Xunit;
global using FakeItEasy;
global using FluentAssertions;
// Project libraries
global using Domain.Entities.Identity;