global using Microsoft.OpenApi.Models;
global using Domain.Entities;
global using Domain.Enums;
global using Domain.Helpers.Pagination;
global using Domain.Dtos.Requests;
global using Domain.Dtos.Responses;
global using Web.Interfaces;
global using Web.Repositories;
global using Web.Extensions;